### ISSUE TITLE
Incorrect highlighting for component names that start with numbers.

### ISSUE THREAD

**Issue by Thom1729** [jcberquist/sublimetext-cfml#62]
Example:

```cfc
component {
    new 123Foo();
}
```

Expected: `123Foo` scoped as `entity.name.class.cfml`.

Actual: `123` as `constant.numeric.cfml`; `Foo` as `variable.other.readwrite.cfml`.

Cause: in cfscript.sublime_syntax:

```yaml
  constructor:
    - match: '\b(new)\s+'
      captures:
        1: keyword.operator.new.cfml
      push:
        - meta_scope: meta.instance.constructor.cfml
        - match: '\b{{identifier}}(?=\()'
          scope: entity.name.class.cfml
          set: constructor-params
        - match: '\b{{identifier}}\b|\.'
          scope: entity.name.class.cfml
        - match: ""
          pop: true
```

Component names may not be identifiers. I can't find the actual rule, but it looks like a component name (or any part of a component path) may contain any identifier character and must not be all-digits, but may begin with a digit.

A cautious regex for this would be: `$[:alnum:]]*[_$[:alpha:]][_$[:alnum:]]*`.

A simpler regex is: `[_$[:alnum:]]*`. This would also match numbers, which would be a syntax error.

EDIT:

I've just noticed a similar issue with struct keys:

```cfc
component {
    x = {
        123Foo: 42,
        456: 'A valid struct'
    }
}
```

Even `456` is a valid struct key.

**Comment by MNU-497** [comment]
If you have something that needs immediate attention please call our main office line: (218) 232-6465 and leave a message. Your time sensitive request will be attended to.
  
 By the time we are through, You'll LIKE IT too,
  
 Jonathan Heintzeman
 www.WeLikeIt.net

**Comment by jcberquist** [comment]
Thanks, I think I will add the alphanumeric check in front of the identifier (your cautious regex):

```yaml
  constructor:
    - match: '\b(new)\s+'
      captures:
        1: keyword.operator.new.cfml
      push:
        - meta_scope: meta.instance.constructor.cfml
        - match: '\b[_$[:alnum:].]*{{identifier}}(?=\()'
          scope: entity.name.class.cfml
          set: constructor-params
        - match: '\b[_$[:alnum:].]*{{identifier}}\b|\.'
          scope: entity.name.class.cfml
        - match: ""
          pop: true
```
